DROP TABLE if exists Cardholder;
DROP TABLE if exists Banks;
DROP TABLE if exists Accounts;
DROP TABLE if exists Ref_Card_Types;
DROP TABLE if exists Cardholder_Cards;
DROP TABLE if exists Cardholder_Banks;
DROP TABLE if exists Merchants_Banks;
DROP TABLE if exists Ref_Currency_Code;
DROP TABLE if exists ATM_Machines;
DROP TABLE if exists Financial_Transactions;
DROP TABLE if exists Merchants;
create table if not exists Cardholder(id bigint, account_nr bigint, country_code bigint, PRIMARY KEY(id));
create table if not exists Banks(id bigint, country_code bigint,  PRIMARY KEY(id));
create table if not exists Accounts(id bigint, cardholder_id bigint, amount bigint,  PRIMARY KEY(id));
create table if not exists Ref_Card_Types(card_type_code bigint, country_code bigint, PRIMARY KEY(card_type_code));
create table if not exists Cardholder_Cards(card_number bigint, cardholder_id bigint, card_type_code bigint, currency_code bigint, PRIMARY KEY(card_number));
create table if not exists Cardholder_Banks(cardholder_bank_id bigint, bank_id bigint, cardholder_id bigint, PRIMARY KEY(cardholder_bank_id));
create table if not exists Merchants_Banks(merchant_id bigint, bank_id bigint, PRIMARY KEY(merchant_id));
create table if not exists Ref_Currency_Code(currency_code bigint, country_code bigint, PRIMARY KEY(currency_code));
create table if not exists ATM_Machines(atm_id bigint, country_code bigint, PRIMARY KEY(atm_id));
create table if not exists Financial_Transactions(transaction_id bigint, amount bigint, atm_id bigint, card_number bigint, card_number_transfer_from bigint, card_number_transfer_to bigint, currency_code bigint, merchant_id bigint, transaction_type_code bigint, PRIMARY KEY(transaction_id));
create table if not exists Merchants(merchant_id bigint, country_code bigint, merchant_category_code bigint, PRIMARY KEY(merchant_id));